CREATE TABLE IF NOT EXISTS log(id INTEGER PRIMARY KEY AUTOINCREMENT,description TEXT;
INSERT or IGNORE INTO log VALUES (1, 'Simon');
INSERT or IGNORE INTO log VALUES (2, 'Max');
INSERT or IGNORE INTO log VALUES (3, 'Ben');